/usr/local/lib/python2.7/site-packages/widgetsnbextension/__init__.py:30: UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[I 19:35:32.900 NotebookApp] Serving notebooks from local directory: /home/ec2-user/corridor
[I 19:35:32.900 NotebookApp] 0 active kernels 
[I 19:35:32.901 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8888/
[I 19:35:32.901 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 19:35:45.470 NotebookApp] 404 GET /notebooks/CorridorBot.ipynb (76.126.141.254): No such file or directory: CorridorBot.ipynb
[W 19:35:45.495 NotebookApp] 404 GET /notebooks/CorridorBot.ipynb (76.126.141.254) 26.45ms referer=None
[I 19:36:04.106 NotebookApp] Creating new notebook in /lib
[W 19:36:07.331 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160530193532 (76.126.141.254) 1.78ms referer=https://tools.zensky.com:8888/notebooks/lib/Untitled.ipynb?kernel_name=python2
[I 19:36:07.546 NotebookApp] Kernel started: c2ac1ca1-aee5-43d2-ab37-2b8e2875905b
[I 19:38:08.419 NotebookApp] Saving file at /lib/test.ipynb
[I 19:44:08.523 NotebookApp] Saving file at /lib/test.ipynb
[I 19:46:25.531 NotebookApp] Saving file at /lib/Corridor/__init__.py
[W 19:46:25.533 NotebookApp] Permission denied: lib/Corridor/__init__.py
[W 19:46:25.534 NotebookApp] 403 PUT /api/contents/lib/Corridor/__init__.py (76.126.141.254) 180.55ms referer=https://tools.zensky.com:8888/edit/lib/Corridor/__init__.py
[I 19:46:29.208 NotebookApp] Saving file at /lib/Corridor/__init__.py
[W 19:46:29.209 NotebookApp] Permission denied: lib/Corridor/__init__.py
[W 19:46:29.209 NotebookApp] 403 PUT /api/contents/lib/Corridor/__init__.py (76.126.141.254) 169.47ms referer=https://tools.zensky.com:8888/edit/lib/Corridor/__init__.py
[I 19:46:33.588 NotebookApp] Saving file at /lib/Corridor/__init__.py
[W 19:46:33.589 NotebookApp] Permission denied: lib/Corridor/__init__.py
[W 19:46:33.589 NotebookApp] 403 PUT /api/contents/lib/Corridor/__init__.py (76.126.141.254) 178.27ms referer=https://tools.zensky.com:8888/edit/lib/Corridor/__init__.py
[I 19:46:37.022 NotebookApp] Saving file at /lib/Corridor/__init__.py
[W 19:46:37.023 NotebookApp] Permission denied: lib/Corridor/__init__.py
[W 19:46:37.023 NotebookApp] 403 PUT /api/contents/lib/Corridor/__init__.py (76.126.141.254) 173.26ms referer=https://tools.zensky.com:8888/edit/lib/Corridor/__init__.py
